vd3.4.1

In [ ]:
import numpy as np
import time
arr = np.arange(100000000, dtype=np.int64)
start_time = time.time()
total=np.int64(0)
for num in arr:
    total+=num
end_time=time.time()
elapsed_time_loop=end_time-start_time
print("Tổng các phần tử mảng arr khi sử dụng vòng lặp", total)
print("Thời gian(giây) khi sử dụng vòng lặp:", elapsed_time_loop)
start_time=time.time()
total=np.sum(arr)
end_time=time.time()
elapsed_time_npsum=end_time-start_time
print("Tổng các phần tử mảng arr khi sử dụng hàm np.sum", total)
print("Thời gian(giây) khi sử dụng np.sum:", elapsed_time_npsum)
num_times_faster=elapsed_time_loop/elapsed_time_npsum
print("Sử dụng vòng lặp chậm hơn: ",int(num_times_faster),"lần")


vd3.4.2

In [2]:
import numpy as np 
import timeit # Import thư viện timeit để đo thời gian thực thi của các đoạn code. 
 
# Tính tổng của mảng sử dụng Numpy 
np_setup = "import numpy as np; np_array = np.arange(1, 1000001)" 
np_code  = "np_sum = np.sum(np_array)" 
np_time  = timeit.timeit(stmt=np_code, setup=np_setup, number=10) 
 
# Tính tổng của danh sách sử dụng List 
list_setup = "list_array = list(range(1, 1000001))" 
list_code = "list_sum = sum(list_array)" 
list_time = timeit.timeit(stmt=list_code, setup=list_setup, 
number=10) 
 
print("Thời gian tính toán của Numpy:", np_time) 
print("Thời gian tính toán của List:", list_time) 
 
print("Numpy tính nhanh hơn List ở lượt chạy là ~ ", int(list_time/np_time), "lần!!")

Thời gian tính toán của Numpy: 0.012955499929375947
Thời gian tính toán của List: 0.12192439998034388
Numpy tính nhanh hơn List ở lượt chạy là ~  9 lần!!


vd3.4.3.1

In [3]:
import numpy as np 
 
arr1 = np.array([1, 2, 3]) 
arr2 = np.array([4, 5, 6]) 
 
#Phép Cộng:Sử dụng hàm np.add() hoặc toán tử '+'. 
Tong = np.add(arr1,arr2) 
#hoặc tong = arr1+arr2 
 
#Phép Trừ: Sử dụng hàm np.subtract() hoặc toán tử '-'. 
Hieu = np.subtract(arr1,arr2) 
#hoặc Tru = arr1-arr2 
 
#Phép Nhân: Sử dụng hàm np.multiply() hoặc toán tử '*' 
Tich = np.multiply(arr1,arr2) 
#Hoặc arr1*arr2 
 
#Phép Chia: Sử dụng hàm np.divide() hoặc toán tử '/' 
Thuong = np.divide(arr1,arr2) 
 
print("Tổng của arr1 + arr2 là:",Tong) 
print("Hiệu của arr1 - arr2 là:",Hieu) 
print("Tích của arr1 * arr2 là:",Tich) 
print("Thương của arr1/arr2 là:",Thuong)

Tổng của arr1 + arr2 là: [5 7 9]
Hiệu của arr1 - arr2 là: [-3 -3 -3]
Tích của arr1 * arr2 là: [ 4 10 18]
Thương của arr1/arr2 là: [0.25 0.4  0.5 ]


vd3.4.3.2

In [4]:
import numpy as np 
arr1=np.random.rand(5) 
arr1

array([0.4553487 , 0.40590978, 0.68163259, 0.2169145 , 0.4577202 ])

In [5]:
arr2=np.random.rand(5) 
arr2

array([0.07132436, 0.50833549, 0.58481198, 0.26737656, 0.98995848])

In [6]:
arr_maximum=np.maximum(arr1,arr2) 
print("Mảng kết quả là:",arr_maximum)

Mảng kết quả là: [0.4553487  0.50833549 0.68163259 0.26737656 0.98995848]


vd3.4.3.3

In [8]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5]) 
 
# Căn bậc hai của các phần tử trong mảng 
kq_can_hai = np.sqrt(arr)  
 
# Lũy thừa 2 của các phần tử trong mảng 
kq_luy_thua_2 = np.power(arr, 2) 
 
# Logarit tự nhiên (cơ số e) của các phần tử trong mảng 
kq_logarit = np.log(arr) 
  
# Giá trị tuyệt đối của các phần tử trong mảng 
kq_tri_tuyet_doi = np.abs(arr) 
 
# Hàm logic NOT (đảo ngược giá trị) của các phần tử trong mảng 
kq_not_logic = np.logical_not(arr) 
#Hàm sin của các phần tử trong mảng 
kq_sin=np.sin(arr) 
print("Căn bậc hai của từng phần tử trong mảng là: ", kq_can_hai)  
print("Lũy thừa bậc hai của từng phần tử trong mảng là: ", kq_luy_thua_2) 
print("Logarit của từng phần tử trong mảng là: ", kq_logarit)  
print("Trị tuyệt đối của từng phần tử trong mảng là: ", kq_tri_tuyet_doi)  
print("Kết quả đảo ngược giá trị của các phần tử trong mảng là:", kq_not_logic) 
print("Kết quả hàm sin của các phần tử trong mảng là:", kq_sin) 


Căn bậc hai của từng phần tử trong mảng là:  [1.         1.41421356 1.73205081 2.         2.23606798]
Lũy thừa bậc hai của từng phần tử trong mảng là:  [ 1  4  9 16 25]
Logarit của từng phần tử trong mảng là:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Trị tuyệt đối của từng phần tử trong mảng là:  [1 2 3 4 5]
Kết quả đảo ngược giá trị của các phần tử trong mảng là: [False False False False False]
Kết quả hàm sin của các phần tử trong mảng là: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


vd3.4.4.3

In [2]:
import numpy as np 
arr = np.array([0,1,2]) 
arr

array([0, 1, 2])

In [3]:
M=np.ones((3,3)) 
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
arr + M

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

vd3.4.4.4

In [ ]:
import numpy as np 
arr1 = np.arange(3) 
arr2=np.arange(3)[:,np.newaxis] 
#np.newaxis sử dụng để cho biết một chiều mới được thêm vào
# #Dấu hai chấm ‘:’ cho biết tất cả các phần tử của chiều đầu tiên được giữ nguyên, 
print(arr1) 
print(arr2)

[0 1 2]
[[0]
 [1]
 [2]]


In [6]:
arr1 + arr2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

vd3.4.4.5

In [7]:
import numpy as np 
arr1=np.ones((2,3)) 
arr2 = np.arange(3) 
print(arr1.shape) 
print(arr2.shape)

(2, 3)
(3,)


In [8]:
arr1+arr2

array([[1., 2., 3.],
       [1., 2., 3.]])

vd3.4.4.6

In [11]:
import numpy as np 
# Tạo mảng dữ liệu với kích thước lớn (1000 phần tử) 
data = np.random.randint(100, 200, size=1000) 
# Tạo một giá trị trung bình (số thực) 
mean_value = np.array([data.mean()]) 
# Tính tỷ lệ phần trăm tăng trưởng bằng cách áp dụng broadcasting 
percentage_growth= (data - mean_value) / mean_value * 100 
# In ra 10 phần tử đầu tiên của mảng dữ liệu và tỷ lệ phần trăm tăng trưởng 
print("Dữ liệu gốc:", data[:10]) 
print("Tỷ lệ phần trăm tăng trưởng:",percentage_growth[:10])

Dữ liệu gốc: [139 104 162 138 176 102 139 143 109 185]
Tỷ lệ phần trăm tăng trưởng: [ -7.39630385 -30.7137813    7.92660991  -8.06251749  17.25360088
 -32.04620858  -7.39630385  -4.73144928 -27.38271309  23.24952366]


# Tính toán nâng cao với numby

vd3.5.1

In [12]:
import numpy as np 
#Mảng đích để lưu trữ kết quả 
output=np.zeros((3,3)) 
#Mảng nguồn arr1, arr2 
arr1=np.array([1,2,3]) 
arr2=np.array([4,5,6]) 
#Thực hiện phép cộng và lưu trữ kết quả vào mảng đích output 
np.add(arr1,arr2, out=output) 
#In kết quả 
print(output)

[[5. 7. 9.]
 [5. 7. 9.]
 [5. 7. 9.]]


vd3.5.2: Khái niệm mặt nạ(Masks)

In [13]:
import numpy as np 
visitors = np.array([10200, 9875, 13567,7900,11200, 8871, 12567])

In [14]:
sum = 0 
for i in visitors: 
    if (i>10000): 
        sum+=i 
print(sum)

47534


Cách giải sử dụng Masks

In [16]:
visitors

array([10200,  9875, 13567,  7900, 11200,  8871, 12567])

In [17]:
mask = visitors > 10000 
mask

array([ True, False,  True, False,  True, False,  True])

In [ ]:
visitors[mask]#Áp dụng mask để lọc các phần  tử thỏa mãn điều kiện (>10000)

array([10200, 13567, 11200, 12567])

In [19]:
#Tính tổng mảng các phần tử được lọc ra 
visitors[mask].sum()

np.int64(47534)

3.5.3. Toán tử so sánh dạng ufuncs

vd3.5.3

In [20]:
# Tạo mảng ngẫu nhiên 
arr1 = np.array([1, 2, 3, 4, 5]) 
arr2 = np.array([5, 4, 3, 2, 1]) 
 
# Toán tử so sánh dạng ufuncs 
result1 = arr1 > arr2   # Lớn hơn 
result2 = arr1 == arr2  # Bằng nhau 
result3 = arr1 <= arr2  # Nhỏ hơn hoặc bằng 
 
print("Kết quả lớn hơn:", result1)     
print("Kết quả bằng nhau:", result2)   
print("Kết quả nhỏ hơn hoặc bằng:", result3)

Kết quả lớn hơn: [False False False  True  True]
Kết quả bằng nhau: [False False  True False False]
Kết quả nhỏ hơn hoặc bằng: [ True  True  True False False]


vd3.5.4.3

In [ ]:
import numpy as np 
arr = np.array([[1,0,3], 
                [0,5,0], 
                [7,0,9]]) 
#Sử dụng phương thức sum kèm theo tham số axis (trục) tương ứng 
print("Số phần tử khác 0 theo mỗi hàng:",np.sum(arr !=0, axis=1))# đếm các phần tử khác 0 theo hàng
print("Số phần tử khác 0 theo mỗi cột:",np.sum(arr!=0, axis=0))# đếm các phần tử khác 0 theo cột

Số phần tử khác 0 theo mỗi hàng: [2 1 2]
Số phần tử khác 0 theo mỗi cột: [2 1 2]


vd3.5.5.1

In [23]:
import numpy as np 
import numpy.ma as ma 
#Tạo một mảng NumPy bình thường 
arr = np.array([1,2,3,4,5,6,7,8,9]) 
# Tạo một mảng mask cho các giá trị không hợp lệ 
mask =arr>6 
masked_arr=np.ma.masked_array(arr,mask) 
masked_arr

masked_array(data=[1, 2, 3, 4, 5, 6, --, --, --],
             mask=[False, False, False, False, False, False,  True,  True,
                    True],
       fill_value=999999)

Đểlấymảngcácphầntửtrảvềchỉ chứacácphầntửhợplệ(mask=false)chúngtathựchiệnnhưsau:

In [25]:
# Lấy các giá trị hợp lệ từ mảng ban đầu bằng cách sử dụng mảng mask 
valid_values = arr[~mask] 
print("Dữ liệu ban đầu:", arr) 
print("Mảng mask:", mask) 
print("Các giá trị hợp lệ từ mảng ban đầu:", valid_values)

Dữ liệu ban đầu: [1 2 3 4 5 6 7 8 9]
Mảng mask: [False False False False False False  True  True  True]
Các giá trị hợp lệ từ mảng ban đầu: [1 2 3 4 5 6]


vd3.6.1.1

In [26]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90]) 
#Truy xuất các phần tử bằng một danh sách các chỉ mục 
indices = [1, 3, 4] 
sub_arr_1 = arr[indices] 
print(sub_arr_1)

[20 40 50]


vd3.6.1.2

In [27]:
#Fancy indexing và boolean 
sub_arr_boolean = arr[arr > 50] 
print("Orignial Array:\n",arr) 
# Boolean Indexing 
print("After Boolean Condition:",arr[arr>50])

Orignial Array:
 [10 20 30 40 50 60 70 80 90]
After Boolean Condition: [60 70 80 90]


In [28]:
#Mảng chỉ mục là mảng 2 chiều 
idx_arr=np.array([[1,2], 
                 [5,6]]) 
sub_arr_2=arr[idx_arr] 
print(sub_arr_2)

[[20 30]
 [60 70]]


3.6.2 Chỉ mục kết hợp

vd3.6.2.1

In [29]:
arr = np.arange(16).reshape(4, 4) 
print("Mảng gốc ban đầu:\n arr = ", arr) 
#Lấy các phần tử arr[3, 1], arr[3, 2] và arr[3, 3] 
sub_arr = arr[3, [1, 2, 3]] 
print("Mảng con: sub_arr = ", sub_arr)

Mảng gốc ban đầu:
 arr =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Mảng con: sub_arr =  [13 14 15]


vd3.6.2.2

In [30]:
# Lấy tất cả các phần tử nằm tại hàng >= 1 và các cột = 1, 2, 3 tương ứng 
sub_arr = arr[1:, [1, 2, 3]] 
print("Mảng con sub_arr:\n", sub_arr)

Mảng con sub_arr:
 [[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


vd3.6.2.3

In [ ]:
#Fancy Indexing và masks 
arr=np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]]) 
 
masks=arr[0,:]%2 == 0   #Lấy hàng 0, chia các phần tử tương ứng  1,2,3 cho 2,  
print("masks:",masks)   #Kết quả là mảng [Flase True False] 
 
sub_arr=arr[:,masks]    # Kết hợp Fancy indexing và mask, dấu ':' ở vị trí hàng 
                        # cho biết lấy toàn bộ các hàng của mảng,  
                        # chỉ mục cột là masks, chỉ có 1 phần tử True ở vị trí 1 
                        # Vì vậy chỉ lấy cột có chỉ mục 1, tức cột 1 
print("Mảng con mới: \n", sub_arr)

masks: [False  True False]
Mảng con mới: 
 [[2]
 [5]
 [8]]
