In [1]:
import numpy
print(numpy.__version__)

2.3.4


Ví dụ: So sánh về lưu trữ bộ nhớ giữ List và Numpy Array

In [2]:
import numpy as np  #import thư viện numpy để tạo và thao tác với mảng NumPy. 
import sys  #import thư viên sys để đo kích thước của đối tượng Python bằng sys.getsizeof().
# Tạo một danh sách Python với 1000 phần tử. 
S = list(range(1000))
# Đo kích thước của mỗi phần tử trong danh sách S 
items_S= sys.getsizeof(S)
print("Kích thước mỗi phẫn tử trong List tính theo bytes: ",items_S)
# Đo kích thước của toàn bộ danh sách S 
S_size = items_S*len(S)
print("Kích thước của toàn bộ List tính theo bytes: ",S_size)
# Tạo một mảng NumPy array với 1000 phần tử 
D= np.arange(1000)
# Đo kích thước của mỗi phần tử trong Numpy array
print("Kích thước mỗi phần tử của mảng Numpy theo bytes: ",D.itemsize)
# Đo kích thước của toàn bộ mảng Numpy array 
array_size=D.itemsize*D.size 
print("Kích thước của toàn bộ mảng Numpy array in bytes: ",array_size) 
print(f"Tỷ lệ (list/array): {S_size / array_size:.2f}")

Kích thước mỗi phẫn tử trong List tính theo bytes:  8056
Kích thước của toàn bộ List tính theo bytes:  8056000
Kích thước mỗi phần tử của mảng Numpy theo bytes:  8
Kích thước của toàn bộ mảng Numpy array in bytes:  8000
Tỷ lệ (list/array): 1007.00


In [3]:
result = 0
for i in range(100):
    result += 1

CHUYỂN ĐỔI DỮ LIỆU

In [5]:
arr = np.array([1.5, 2.7, 3.2]) # Khởi tạo một mảng NumPy mới (arr). Do các giá trị đầu vào là số thực, NumPy mặc định gán dtype là float64.
arr

array([1.5, 2.7, 3.2])

In [ ]:
# kIỂM TRA KIỂU DỮ LIỆU CÁC PHẦN TỬ CỦA ARRAY
arr.dtype

dtype('float64')

In [7]:
# THỰC HIỆN CHUYỂN KIỂU DỮ LIỆU
arr_int = arr.astype(np.int32) # Sử dụng phương thức .astype() để tạo một bản sao mới của mảng arr nhưng với kiểu dữ liệu là int32 (số nguyên 32-bit).’’’
print(arr_int, arr_int.dtype)

[1 2 3] int32


In [8]:
import numpy as np 
 
#Kiểu dữ liệu nguyên: 
arr_int=np.array([1,2,3,4],dtype=np.int32) 
arr_int.dtype

dtype('int32')

In [9]:
#Kiểu dữ liệu số thực: 
arr_float = np.array([1.1, 2.2, 3.3], dtype=np.float64) 
arr_float.dtype  # Output: float64

dtype('float64')

In [10]:
#Kiểu dữ liệu chuỗi (string): 
arr_string = np.array(['apple', 'banana', 'orange'], 
dtype=np.str_) 
arr_string.dtype  # Output: <U6

dtype('<U6')

In [11]:
#Kiểu dữ liệu logic (boolean): 
arr_bool = np.array([True, False, True], dtype=np.bool_) 
arr_bool.dtype  # Output: bool

dtype('bool')

In [12]:
# HÀM full()
import numpy as np 
# Tạo mảng kích thước 5x5 các số thực có giá trị  = 100 
np.full((5,5),100,dtype=float)

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [13]:
# HÀM np.arange()
import numpy as np 
# Tạo mảng chứa các số từ 0 đến 9 
arr_1 =np.arange(10) 
print(arr_1)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
import numpy as np 
# Tạo mảng chứa các số từ 5 đến 14 với bước nhảy là 2 
arr_2 =np.arange(5, 15, 2) 
print(arr_2)

[ 5  7  9 11 13]


In [15]:
import numpy as np 
# Tạo mảng chứa các số từ 0 đến 1 với bước nhảy là 0.1 và kiểu dữ liệu là float. 
arr_3 =np.arange(0, 1, 0.1, dtype=float) 
print(arr_3)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


HÀM np.linspace()

In [16]:
import numpy as np 
# Tạo mảng chứa 5 giá trị từ 0 đến 10 (gồm giá trị kết thúc) 
arr_1 = np.linspace(0, 10, 5) 
print(arr_1) 

[ 0.   2.5  5.   7.5 10. ]


In [17]:
# Tạo mảng chứa 10 giá trị từ 0 đến 1 (không chứa giá trị # kết thúc) 
arr_2 = np.linspace(0, 1, 10, endpoint=False) 
print(arr_2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [18]:
# Tạo mảng chứa 100 giá trị từ 1 đến 10 và trả về kích thước bước. 
arr_3, step = np.linspace(1, 10, 100, retstep=True) 
print(arr_3) 
print("Step size:", step)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

HÀM np.random.random()

In [19]:
import numpy as np 
# Tạo môt mảng 1 chiều gồm 5 giá trị ngẫu nhiên từ phân phối đều 
#trong khoảng từ 0 đến 1 
arr_5 = np.random.random(5) 
print(arr_5)

[0.53991901 0.20067851 0.97290583 0.12983111 0.24131823]


HÀM np.random.normal()

In [20]:
import numpy as np 
# Tạo môt mảng 100 giá trị ngẫu nhiên từ phân phối chuẩn với # trung bình 0 và độ lệch chuẩn là 1. 
arr_6 = np.random.normal(loc=0.0, scale=1.0, size=100) 
print(arr_6)

[ 2.0304196   1.68448323 -0.29204523 -0.85064843  1.87167076  1.15605145
 -1.68362807  0.39242841  1.39457397  1.28395487  0.51374871 -1.27508859
  0.35906243 -0.66185754  0.40863979 -0.78180369  0.7538171   0.84309226
 -0.09068722  1.2323436   0.02864694  0.92630438 -1.2300684   1.17545659
 -0.42215995  0.87510008 -0.84718246  0.67988959 -0.64146758 -0.22506146
 -0.2041787  -0.34431141 -1.74422159  0.29331357 -1.96951879 -0.79418654
  1.56725911 -1.37465023  0.551913    1.59078955  0.57747982 -0.40024042
  1.78439931  0.89144785 -0.21430258  0.91881339 -1.16205587 -0.68161607
  0.26471902  1.49492453 -0.01983521  0.07265627  1.00334023  0.42593922
 -0.48368945 -0.80120151 -1.94265997  0.48529149  1.51361208 -0.90910659
  0.13601355  0.10631814  0.51835306 -0.07241882  1.03777021  1.99351449
 -0.72936874  3.13035437  1.8150574  -0.10685777  0.01156912  1.20250278
 -2.05060473 -1.70945548 -1.37091927 -1.16118753 -1.02083443 -0.05151099
  1.89364563  0.09013387  0.25942458  1.74610821  0

8. Hàmnp.random.randint()

In [21]:
import numpy as np 
# Tạo mảng 2 chiều 3x3 gồm các số nguyên ngẫu nhiên từ 0 9 
arr_7 = np.random.randint(0,10,(3,3)) 
print(arr_7)

[[3 0 9]
 [6 8 0]
 [5 0 8]]


9. Hàmnp.eye()

In [22]:
import numpy as np 
# Tạo mảng 2 chiều 3x3  
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

10. Hàmnp.empty()

In [23]:
import numpy as np 
# Tạo mảng rỗng gồm 5 phần tử, giá trị của 5 phần tử này có thể là bất kỳ giá trị 
# nào đã lưu trong bộ nhớ trước đó. 
np.empty(5)

array([0.53991901, 0.20067851, 0.97290583, 0.12983111, 0.24131823])

Mảng con 1 chiều

In [8]:
import numpy as np 
A=np.arange(10) 
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
A[:5]       # 5 phần tử đầu tiên của mảng A

array([0, 1, 2, 3, 4])

In [10]:
A[5:]  #Các phần tử ở sau vị trí 5

array([5, 6, 7, 8, 9])

In [11]:
A[4:7]  #Các hần tử ở vị trí thứ thứ năm đến thứ 7

array([4, 5, 6])

Mảng con đa chiều

In [ ]:
import numpy as np
B=np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
B

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [ ]:
B[:2,:3] # hai dòng 3 cột

array([[1, 2, 3],
       [5, 6, 7]])

In [3]:
B[:3,::2]   # lấy các hàng tuè bắt đầu từ 0-hàng 3(ko bao gồm hàm này)
            # lấy các cột với bước nhảy là 2 bắt đầu từ cột 0

array([[1, 3],
       [5, 7],
       [9, 1]])

In [4]:
B[ ::-1, ::-1]  # Lấy các hàng từ cuối lên bước nhảy là -1
                # Lấy các cột từ bên phải sang, bước nhảy là -1

array([[2, 1, 0, 9],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

TRUY CẬP CÁC HÀNG VÀ CỘT CỦA MẢNG

vd3.3.2.5

In [12]:
arr=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) 
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print("Cột đầu tiên của mảng arr là: ",arr[:,0])    
print("Hàng đầu tiên của mảng arr là:",arr[0,:]) 
print("Hàng đầu tiên của mảng arr là:",arr[0])

Cột đầu tiên của mảng arr là:  [1 4 7]
Hàng đầu tiên của mảng arr là: [1 2 3]
Hàng đầu tiên của mảng arr là: [1 2 3]


vd3.3.3.1

In [7]:
import numpy as np
arr_2d=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr_view=arr_2d[:2, :2].view()
print(arr_view)

[[1 2]
 [4 5]]


In [14]:
# Thay đổi giá trị trong view 
arr_view[0, 0] = 100 #Chỉnh sửa phần tử ở dòng 0, cột 0 thành 10. 
print(arr_view)      #in ra mảng con sau khi chỉnh sửa.

[[100   2]
 [  4   5]]


In [15]:
print("Mảng gốc sau khi thay đổi giá trị trong view:") 
print(arr_2d)           #in ra mảng arr ban đầu. 

Mảng gốc sau khi thay đổi giá trị trong view:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


vd3.3.3.2

In [16]:
sub_arr=arr[:2,:2] #slicing mảng con lấy 2 dòng, 2 cột của mảng arr 
print(sub_arr)     #in mảng con arr_con vừa được slicing

[[1 2]
 [4 5]]


In [17]:
sub_arr[0,0]=10  #Chỉnh sửa phần tử ở dòng 0, cột 0 của mảng con thành 10. 
print(sub_arr)  #in ra mảng con sau khi chỉnh sửa.

[[10  2]
 [ 4  5]]


In [18]:
print(arr)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


HÀM np.copy

In [19]:
sub_arr_copy=arr[:2,:2].copy()  #Thêm phương thức copy(). 
print(sub_arr_copy)     #in mảng con vừa được copy.

[[10  2]
 [ 4  5]]


In [20]:
sub_arr_copy[0,0]=10    #sửa phần tử ở dòng 0, cột 0 của mảng                
                        # copy thành 10. 
print(sub_arr_copy)

[[10  2]
 [ 4  5]]


In [21]:
print(arr)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


vd3.3.3.4

In [22]:
arr=np.arange(1,10)     #Tạo mảng một chiều arr có 9 phần tử từ 1-9 
grid= arr.reshape((3,3))#chuyển đổi mảng arr thành mảng grid, 3x3 
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

vd3.3.3.5

In [23]:
x = np.array([1, 2, 3]) 
x.reshape((1, 3)) #tạo ma trận hàng thông qua reshape.

array([[1, 2, 3]])

In [24]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [25]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [26]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

vd3.3.4.1

In [27]:
x = np.array([1, 2, 3]) 
y = np.array([4, 5, 6]) 
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

vd3.3.4.2

In [29]:
import numpy as np 
a = np.array([[1, 2], 
            [3, 4]]) 
b = np.array([[5, 6], 
            [7, 8]]) 
# Kết hợp theo chiều đầu tiên (trục dọc/ trục 0) của mảng 
c = np.vstack((a, b))  
# Kết hợp theo chiều ngang (trục ngang/ trục 1) của mảng 
d = np.hstack((a,b)) 
print(c) 
print(d) 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


vd3.3.4.3

In [30]:
import numpy as np 
arr = np.arange(10)   #Tạo mảng arr gồm 10 phần tử từ 0-9 
sub_arr1=np.split(arr,[3, 6]) #chia mảng arr theo chỉ mục [3, 6]  
#Phần đầu tiên bắt đầu từ chỉ mục 0 và kết thúc trước chỉ mục 3. 
#Phần thứ hai bắt đầu từ chỉ mục 3 và kết thúc trước chỉ mục 6. 
sub_arr2=np.split(arr,2) #chia mảng arr thành 2 phần bằng nhau  
print("Mảng con sub_arr1 là:", sub_arr1, "\n") 
print("Mảng con sub_arr2 là:", sub_arr2)

Mảng con sub_arr1 là: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])] 

Mảng con sub_arr2 là: [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


vd3.3.4.4

In [31]:
import numpy as np 
arr = np.arange(16).reshape((4,4)) 
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
upper,lower = np.vsplit(arr,2) #Tách theo trục ngang 
print("Kết quả sau khi tách từ mảng ban đầu \n") 
print(upper,"\n") 
print(lower,"\n")

Kết quả sau khi tách từ mảng ban đầu 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]] 



In [33]:
left,right=np.hsplit(arr,2)   #Tách theo trục dọc 
print("Kết quả sau khi tách từ mảng ban đầu \n") 
print(left,"\n") 
print(right,"\n")

Kết quả sau khi tách từ mảng ban đầu 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 



vd3.3.5.1

In [34]:
import numpy as np 
arr=np.array([1,2,3]) 
new_arr=np.append(arr,4) 
print(arr) 
print(new_arr)

[1 2 3]
[1 2 3 4]


vd3.3.5.2

In [35]:
#Thêm phần tử vào vị trí cụ thể trong mảng 1 chiều: 
arr = np.array([1, 2, 3, 4, 5]) 
new_element = 10 
index_to_insert = 2 
new_arr = np.insert(arr, index_to_insert, new_element)
print(new_arr)

[ 1  2 10  3  4  5]


In [36]:
#Thêm phần tử vào vị trí cụ thể trong mảng 2 chiều: 
arr_2d = np.array([[1, 2], [3, 4], [5, 6]]) 
new_element = [7, 8] 
row_to_insert = 1 
new_arr_2d=np.insert(arr_2d,row_to_insert,new_element,axis=0) 
print(new_arr_2d)

[[1 2]
 [7 8]
 [3 4]
 [5 6]]


vd3.3.6.1

In [37]:
#Tìm chỉ mục (vị trí) phần tử trong mảng 1 chiều: 
arr = np.array([1, 2, 3, 4, 5]) 
indices = np.where(arr==3) 
indices

(array([2]),)

In [38]:
arr = np.array([1, 2, 3, 4, 5]) 
indices = np.argwhere(arr==3) 
indices

array([[2]])

vd3.3.6.3

In [39]:
arr = np.array([1, 5, 2, 3, 4]) 
max_idx = np.argmax(arr) 
min_idx = np.argmin(arr) 
print(max_idx) 
print(min_idx)

1
0


vd3.3.6.4

In [40]:
arr = np.array([1, 2, 3, 4, 5]) 
sorted_arr = np.sort(arr) 
sorted_arr

array([1, 2, 3, 4, 5])

In [41]:
arr = np.array([1, 2, 3, 4, 5]) 
arr.sort() 
arr

array([1, 2, 3, 4, 5])

Sửdụnghàmnumpy,np.sort()vàđảongượcmảng:

In [42]:
arr = np.array([3, 1, 4, 2, 5]) 
sorted_arr_descending= np.sort(arr)[::-1]  
sorted_arr_descending

array([5, 4, 3, 2, 1])

Sửdụngphươngthứcsort()củamảngvàđảongượcmảng

In [43]:
arr = np.array([3, 1, 4, 2, 5]) 
arr.sort()                   
arr[::-1]

array([5, 4, 3, 2, 1])

vd3.3.7.1

In [44]:
#Xóa một phần tử ở vị trí trong mảng 
arr = np.array([3, 1, 4, 2, 5]) 
idx_to_delete = 2                 #Xóa phần tử 4 ở chỉ mục 2. 
new_arr=np.delete(arr,idx_to_delete) 
new_arr

array([3, 1, 2, 5])

In [46]:
#Xóa nhiểu phần tử trong mảng 
arr = np.array([3, 1, 4, 2, 5]) 
idx_to_delete = [1, 3] 
new_arr = np.delete(arr, idx_to_delete) 
new_arr

array([3, 4, 5])

In [48]:
#Xóa phần tử trên mảng 2 chiều 
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
row_idx_to_delete = 1 
new_arr_2d = np.delete(arr_2d, row_idx_to_delete, axis=0)

vd3.3.8.2

In [2]:
import numpy as np 
 
# Định nghĩa kiểu dữ liệu cho một Structured Array 
dtype = [('name', 'U20'), ('age', int), ('height', float)] 
 
# Tạo một Structured Array 
data = np.array([('Minh', 22, 165.5), 
                 ('Lan', 40, 160.0), 
                 ('Linh', 31, 165.0), 
                 ('Lương',18,166.5), 
                 ('Thanh',50, 170.0)], dtype=dtype) 
# Truy cập các trường bằng tên 
print(data['name'])    # In ra mảng 'name' 
print(data['age'])     # In ra mảng 'age' 
print(data['height'])  # In ra mảng 'height'

['Minh' 'Lan' 'Linh' 'Lương' 'Thanh']
[22 40 31 18 50]
[165.5 160.  165.  166.5 170. ]
