# 4.5.1

vd4.5.1.1

In [ ]:
import pandas as pd
import numpy as np
rng=np.random.RandomState(100) #Tạo một mảng NumPy ngẫu nhiên cố định
arr1=rng.randint(0,10,4) #mảng NumPy 1 chiều 4 số ngẫu nhiên từ 0->10
arr2=rng.randint(0,10,(3,4)) #mảng 2 chiều 3x4 các số ngẫu nhiên từ 0->10, k lấy 10

In [2]:
arr1

array([8, 8, 3, 7], dtype=int32)

In [3]:
arr2

array([[7, 0, 4, 2],
       [5, 2, 2, 2],
       [1, 0, 8, 4]], dtype=int32)

In [4]:
sr=pd.Series(arr1) #Tạo một Series Pandax từ mảng Numpy arr1
df=pd.DataFrame(arr2,columns=['A','B','C','D']) #Tạo DataFrame từ arr2
print("Series:\n",sr)
print("DataFrame:\n",df)

Series:
 0    8
1    8
2    3
3    7
dtype: int32
DataFrame:
    A  B  C  D
0  7  0  4  2
1  5  2  2  2
2  1  0  8  4


vd4.5.1.2a

In [5]:
import pandas as pd
import numpy as np
s1=pd.Series([2,4,6], index=['a','b','c'])
s2=pd.Series([1,3,5], index=['b','c','d'])

In [6]:
s1

a    2
b    4
c    6
dtype: int64

In [7]:
s2

b    1
c    3
d    5
dtype: int64

In [ ]:
s1+s2 # Phép cộng với việc căn chỉnh theo index

a    NaN
b    5.0
c    9.0
d    NaN
dtype: float64

In [9]:
s3=pd.Series([2,4,6], index=['a','b','c']) # Khởi tạo Series s3, với index a,b,c
s4=pd.Series([1,3,5], index=['b','c','d'])

In [10]:
s3

a    2
b    4
c    6
dtype: int64

In [11]:
s4

b    1
c    3
d    5
dtype: int64

In [12]:
s3.add(s4, fill_value=0)

a    2.0
b    5.0
c    9.0
d    5.0
dtype: float64

vd4.5.1.2.b

In [15]:
#Ví dụ 4.5.1.2 #Số liệu top 5 dân số tỉnh thành Việt Nam
population = pd.Series({'TP.Hồ Chí Minh':9411805,
'Hà Nội':8330830,
'Thanh Hóa':3720000,
'Nghệ An':3410000,
'Đồng Nai':3097107})
#Số liệu về top 5 diện tích tỉnh/thành Việt Nam
area=pd.Series({'Nghệ An':16493,
'Gia Lai':15536.9,
'Sơn La':14174.4,
'Đăk Lăk':13030.5,
'Thanh Hóa':11132.2})
print("Top 5 tỉnh/tp đông dân nhất Việt Nam 2023:\n",population)
print("Top 5 tỉnh/tp diện tích lớn nhất Việt Nam 2023:\n",area)

Top 5 tỉnh/tp đông dân nhất Việt Nam 2023:
 TP.Hồ Chí Minh    9411805
Hà Nội            8330830
Thanh Hóa         3720000
Nghệ An           3410000
Đồng Nai          3097107
dtype: int64
Top 5 tỉnh/tp diện tích lớn nhất Việt Nam 2023:
 Nghệ An      16493.0
Gia Lai      15536.9
Sơn La       14174.4
Đăk Lăk      13030.5
Thanh Hóa    11132.2
dtype: float64


vd4.5.1.3

In [13]:
#Tạo 2 Series A, B và tính tổng các giá trị
A=pd.Series([1,3,5],index=[0,1,2])
B=pd.Series([2,4,6],index=[1,2,3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [14]:
#Sử dụng ufuncs, truyền tham số fill_value vào.
A.add(B,fill_value=0)

0    1.0
1    5.0
2    9.0
3    6.0
dtype: float64

vd4.5.1.4

In [17]:
#Tạo 2 DataFrame Adf, Bdf và tính tổng các giá trị
import pandas as pd
import numpy as np
Adf=pd.DataFrame(np.random.randint(0,10,(2,2)), columns=['A','B'])
Bdf=pd.DataFrame(np.random.randint(0,10,(3,3)),columns=['B','A','C'])
print("Adf:\n",Adf)
print("Bdf:\n",Bdf)
print("\nAdf+Bdf: \n", Adf+Bdf)

Adf:
    A  B
0  6  8
1  0  8
Bdf:
    B  A  C
0  4  4  8
1  1  2  0
2  9  4  8

Adf+Bdf: 
       A     B   C
0  10.0  12.0 NaN
1   2.0   9.0 NaN
2   NaN   NaN NaN


In [18]:
print("Adf+Bdf(filled A):\n", Adf.add(Bdf,fill_value=0))

Adf+Bdf(filled A):
       A     B    C
0  10.0  12.0  8.0
1   2.0   9.0  0.0
2   4.0   9.0  8.0


# 4.5.2 Xử lý dữ liệu giữa Series và Dataframe

vd4.5.2.1

In [19]:
#Tạo một mảng NumPy 2 chiều (3,4) từ 10 phân tử ngẫu nhiên 0-->9
arr = np.random.randint(10,size=(3,4))
arr

array([[8, 6, 5, 2],
       [7, 7, 6, 2],
       [5, 4, 1, 4]], dtype=int32)

In [22]:
arr[0]

array([8, 6, 5, 2], dtype=int32)

In [20]:
arr-arr[0]

array([[ 0,  0,  0,  0],
       [-1,  1,  1,  0],
       [-3, -2, -4,  2]], dtype=int32)

In [21]:
#Tạo DataFrame df từ mảng NumPy arr, với các cột là P, Q, M, N
df = pd.DataFrame(arr,columns=['P','Q','M','N'])
print("df:\n",df)
#Tính toán hiệu của df với phần tử tương ứng trong hàng đầu của nó
df-df.iloc[0]

df:
    P  Q  M  N
0  8  6  5  2
1  7  7  6  2
2  5  4  1  4


P  Q  M  N
0  0  0  0  0
1 -1  1  1  0
2 -3 -2 -4  2

In [ ]:
df.iloc[0] # Lấy hàng đầu tiên của dataframe df dưới dạng series

P    8
Q    6
M    5
N    2
Name: 0, dtype: int32

In [24]:
df.iloc[0].index    #index of series lấy từ hnagf đầu tiên of dataframe df

Index(['P', 'Q', 'M', 'N'], dtype='object')

In [25]:
df.columns

Index(['P', 'Q', 'M', 'N'], dtype='object')

In [26]:
df.iloc[0].index=df.columns

In [27]:
df.iloc[0].name

0

In [28]:
df

P  Q  M  N
0  8  6  5  2
1  7  7  6  2
2  5  4  1  4

In [30]:
df-df.iloc[0]

P  Q  M  N
0  0  0  0  0
1 -1  1  1  0
2 -3 -2 -4  2

In [31]:
df

P  Q  M  N
0  8  6  5  2
1  7  7  6  2
2  5  4  1  4

In [32]:
df['Q'].index=df.index

# 4.5.3.Xử lý dữ liệu bị thiếu trong pandas

vd4.5.3.2

In [33]:
arr_nan=np.array([1,np.nan,3,4])
print(f"Mảng gốc: {arr_nan}")

Mảng gốc: [ 1. nan  3.  4.]


In [35]:
# Tính chất
arr_nan.sum(),arr_nan.max(), arr_nan.min()

(np.float64(nan), np.float64(nan), np.float64(nan))

In [37]:
#giải pháp nánum() (bỏ qua NaN)
np.nansum(arr_nan), np.nanmin(arr_nan)

(np.float64(8.0), np.float64(1.0))

vd4.5.3.3

In [38]:
import pandas as pd
sr_auto=pd.Series([1,2,np.nan,4,None])
sr

0    8
1    8
2    3
3    7
dtype: int32

vd4.5.3.6

In [40]:
data=pd.Series([1,np.nan,2,None,3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

4.8 Thống kê và phân nhóm dữ liệu với pandas - tiết 9

4.8.1 Thống kê dữ liệu: Phương thức descride()

- count số lượng quan sát
- meant điểm tb
- std độ lẹch chuẩn

In [20]:
import pandas as pd

data = {
    'Tuổi': [16,17,16,18,17,],
    'Chiều cao': [165,170,160,172,168],
    'Cân nặng': [55,60,52,65,58]
}
df = pd.DataFrame(data)
df

Tuổi  Chiều cao  Cân nặng
0    16        165        55
1    17        170        60
2    16        160        52
3    18        172        65
4    17        168        58

In [21]:
# Thống kê mô tả
df.describe()

Tuổi   Chiều cao   Cân nặng
count   5.00000    5.000000   5.000000
mean   16.80000  167.000000  58.000000
std     0.83666    4.690416   4.949747
min    16.00000  160.000000  52.000000
25%    16.00000  165.000000  55.000000
50%    17.00000  168.000000  58.000000
75%    17.00000  170.000000  60.000000
max    18.00000  172.000000  65.000000

In [22]:
df.info

<bound method DataFrame.info of    Tuổi  Chiều cao  Cân nặng
0    16        165        55
1    17        170        60
2    16        160        52
3    18        172        65
4    17        168        58>

vd minh họa IQR

In [23]:
df

Tuổi  Chiều cao  Cân nặng
0    16        165        55
1    17        170        60
2    16        160        52
3    18        172        65
4    17        168        58

In [24]:
q1 = df['Chiều cao'].quantile(0.25)
q3 = df['Chiều cao'].quantile(0.75)
iqr = q3 - q1
iqr

np.float64(5.0)

4.8.2 Phân nhóm dữ liệu với groupby()

vd4.8.2.1

In [25]:
# Tạo DataFrame đơn giản để minh họa groupby (Ví dụ 4.8.2.1)
df_data = {
    'key':['A','B','C','A','B','C'],
    'data':range(6)
}
df = pd.DataFrame(df_data, columns=['key','data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [26]:
# 1. Tạo đối tượng GroupBy (Chưa tính toán)
grouped = df.groupby('key')
print("Đối tượng GroupBy (Lazy Evaluation):", type(grouped))

Đối tượng GroupBy (Lazy Evaluation): <class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [27]:
# 2. Áp dụng phép tổng hợp (Tính toán thực tế)
print("\nKết quả sau khi áp dụng sum() (Bước Apply và Combine):")
print(grouped.sum())


Kết quả sau khi áp dụng sum() (Bước Apply và Combine):
     data
key      
A       3
B       5
C       7


In [28]:
#Xem từng nhóm dữ liệu
grouped.get_group('A')          #các hàng có key='A" được gom thành một nhóm

key  data
0   A     0
3   A     3

In [29]:
grouped.get_group('B')

key  data
1   B     1
4   B     4

In [30]:
grouped.get_group('C')

key  data
2   C     2
5   C     5

### C. CÁC TÍNH NĂNG CƠ BẢN

VD4.8.2.2

In [31]:
import pandas as pd

data = {'Tên hs':['Bình', 'Hoa','Minh','Lan','Vân'],
        'Môn':['Toán','Lý','Toán','Hóa','Lý'],
        'Điểm':[8,9,7,6,8]
}
df=pd.DataFrame(data)
df


Tên hs   Môn  Điểm
0   Bình  Toán     8
1    Hoa    Lý     9
2   Minh  Toán     7
3    Lan   Hóa     6
4    Vân    Lý     8

In [32]:
# Phân nhóm dữ liệu theo cột 'Môn'
grouped_mon = df.groupby('Môn')

In [33]:
# Truy cập cột 'Điểm' của từng nhóm
for ten_mon, df_nhom in grouped_mon: #ten_mon: Là nhãn nhóm (dữ liệu chuỗi: 'Toán', 'Lý', 'Hóa').
                                     #df_nhom: Là dữ liệu của nhóm (đối tượng DataFrame có thể tính toán).
    print(f"Nhóm: {ten_mon} :")
    print(df_nhom[['Điểm']])

Nhóm: Hóa :
   Điểm
3     6
Nhóm: Lý :
   Điểm
1     9
4     8
Nhóm: Toán :
   Điểm
0     8
2     7


VD4.8.2.3

In [34]:
import numpy as np
import pandas as pd

df = pd.DataFrame(
    {
        'key':['A','B','C','A','B','C'],
        'giatri_1':np.random.randint(10,100,6),
        'giatri_2':np.random.randint(0,10,6)
    },
    columns=['key','giatri_1','giatri_2']
)
print("df: \n",df)

df: 
   key  giatri_1  giatri_2
0   A        40         1
1   B        76         6
2   C        66         3
3   A        76         4
4   B        18         8
5   C        55         9


In [35]:
for key, giatri in df.groupby('key'):
    print("\nkey: ",key)
    print("value: \n",giatri)


key:  A
value: 
   key  giatri_1  giatri_2
0   A        40         1
3   A        76         4

key:  B
value: 
   key  giatri_1  giatri_2
1   B        76         6
4   B        18         8

key:  C
value: 
   key  giatri_1  giatri_2
2   C        66         3
5   C        55         9


VD4.8.2.4

In [36]:
print(df.groupby('key').get_group('A'))

  key  giatri_1  giatri_2
0   A        40         1
3   A        76         4


### 4.8.3 CÁC HÀM TỔNG HỢP VÀ BIẾN ĐỔI

vd4.8.2.5

In [37]:
df

key  giatri_1  giatri_2
0   A        40         1
1   B        76         6
2   C        66         3
3   A        76         4
4   B        18         8
5   C        55         9

In [38]:
grouped = df.groupby('key')
result = grouped.aggregate({'giatri_1': ['sum', 'mean']}) #Ap dụng hàm sum() , mean() trên cột giatri_1 theo từng nhóm
result

giatri_1      
         sum  mean
key               
A        116  58.0
B         94  47.0
C        121  60.5

2. phương thức agg()

vd4.8.2.6

In [39]:
df

key  giatri_1  giatri_2
0   A        40         1
1   B        76         6
2   C        66         3
3   A        76         4
4   B        18         8
5   C        55         9

In [40]:
groupped = df.groupby('key')
result = grouped.agg(
    {
        #'giatri_1':sum, 'giatri_2':lambda x:x.mean() #truyền hàm python gốc 'sum' để tính tổng cột 'giatri_1' theo nhóm đã được nhóm
        'giatri_1':lambda x:x.sum(),  #việc phải tạo và gọi hàm lambda cho mỗi nhóm sẽ làm giảm hiệu suất so với cơ chế tối ưu hóa nội bộ của Pandas.
        'giatri_2':lambda x:x.mean()
    })
result

giatri_1  giatri_2
key                    
A         116       2.5
B          94       7.0
C         121       6.0

In [41]:
result = grouped.agg({'giatri_1': "sum", 'giatri_2': "mean"})       #Dùng Chuỗi ký tự ("sum" thay cho hàm python sum Đối với cột giatri_1) để tôi ưu hóa hiệu suất
result

giatri_1  giatri_2
key                    
A         116       2.5
B          94       7.0
C         121       6.0

3 Phương thức transform()

VD4.8.2.7

In [46]:
grouped = df.groupby('key')


In [47]:
normalized_temp = df['giatri_1']
normalized_temp

0    40
1    76
2    66
3    76
4    18
5    55
Name: giatri_1, dtype: int32

In [48]:
normalized_ch = (df['giatri_1'] - grouped['giatri_1'].transform('mean')) / grouped['giatri_1'].transform('std')
normalized_ch

0   -0.707107
1    0.707107
2    0.707107
3    0.707107
4   -0.707107
5   -0.707107
Name: giatri_1, dtype: float64

In [49]:
normalized=normalized_temp=normalized_ch
normalized

0   -0.707107
1    0.707107
2    0.707107
3    0.707107
4   -0.707107
5   -0.707107
Name: giatri_1, dtype: float64

4. Phương thức filter()

In [50]:
# Lọc các nhóm có giá trị 2 trung bình lớn hơn 5
filtered = grouped.filter(lambda x: x['giatri_2'].mean() > 5)

# In nội dung của DataFrame 'filtered'
print("filtered: \n", filtered)

filtered: 
   key  giatri_1  giatri_2
1   B        76         6
2   C        66         3
4   B        18         8
5   C        55         9


5. Phương thức apply()

In [51]:
# DataFrame gốc
df = pd.DataFrame({'key': ['A','A','B','B', 'C', 'C'],
                   'value': [1, 2, 3, 4, 5, 6]})
df


key  value
0   A      1
1   A      2
2   B      3
3   B      4
4   C      5
5   C      6

In [52]:
# Gom nhóm dữ liệu theo cột 'key'
grouped = df.groupby('key')

In [53]:
# Áp dụng hàm sum() lên cột 'value' của mỗi nhóm
result = grouped['value'].apply(np.sum)    #Sử dụng phương thức apply để áp dung hàm tùy chỉnh np.sum() lên cột giá trị

# In kết quả
print("Result: \n", result)

Result: 
 key
A     3
B     7
C    11
Name: value, dtype: int64


4.8.4 Case Study