# 4.5.1

vd4.5.1.1

In [ ]:
import pandas as pd
import numpy as np
rng=np.random.RandomState(100) #Tạo một mảng NumPy ngẫu nhiên cố định
arr1=rng.randint(0,10,4) #mảng NumPy 1 chiều 4 số ngẫu nhiên từ 0->10
arr2=rng.randint(0,10,(3,4)) #mảng 2 chiều 3x4 các số ngẫu nhiên từ 0->10, k lấy 10

In [2]:
arr1

array([8, 8, 3, 7], dtype=int32)

In [3]:
arr2

array([[7, 0, 4, 2],
       [5, 2, 2, 2],
       [1, 0, 8, 4]], dtype=int32)

In [4]:
sr=pd.Series(arr1) #Tạo một Series Pandax từ mảng Numpy arr1
df=pd.DataFrame(arr2,columns=['A','B','C','D']) #Tạo DataFrame từ arr2
print("Series:\n",sr)
print("DataFrame:\n",df)

Series:
 0    8
1    8
2    3
3    7
dtype: int32
DataFrame:
    A  B  C  D
0  7  0  4  2
1  5  2  2  2
2  1  0  8  4


vd4.5.1.2a

In [5]:
import pandas as pd
import numpy as np
s1=pd.Series([2,4,6], index=['a','b','c'])
s2=pd.Series([1,3,5], index=['b','c','d'])

In [6]:
s1

a    2
b    4
c    6
dtype: int64

In [7]:
s2

b    1
c    3
d    5
dtype: int64

In [ ]:
s1+s2 # Phép cộng với việc căn chỉnh theo index

a    NaN
b    5.0
c    9.0
d    NaN
dtype: float64

In [9]:
s3=pd.Series([2,4,6], index=['a','b','c']) # Khởi tạo Series s3, với index a,b,c
s4=pd.Series([1,3,5], index=['b','c','d'])

In [10]:
s3

a    2
b    4
c    6
dtype: int64

In [11]:
s4

b    1
c    3
d    5
dtype: int64

In [12]:
s3.add(s4, fill_value=0)

a    2.0
b    5.0
c    9.0
d    5.0
dtype: float64

vd4.5.1.2.b

In [15]:
#Ví dụ 4.5.1.2 #Số liệu top 5 dân số tỉnh thành Việt Nam
population = pd.Series({'TP.Hồ Chí Minh':9411805,
'Hà Nội':8330830,
'Thanh Hóa':3720000,
'Nghệ An':3410000,
'Đồng Nai':3097107})
#Số liệu về top 5 diện tích tỉnh/thành Việt Nam
area=pd.Series({'Nghệ An':16493,
'Gia Lai':15536.9,
'Sơn La':14174.4,
'Đăk Lăk':13030.5,
'Thanh Hóa':11132.2})
print("Top 5 tỉnh/tp đông dân nhất Việt Nam 2023:\n",population)
print("Top 5 tỉnh/tp diện tích lớn nhất Việt Nam 2023:\n",area)

Top 5 tỉnh/tp đông dân nhất Việt Nam 2023:
 TP.Hồ Chí Minh    9411805
Hà Nội            8330830
Thanh Hóa         3720000
Nghệ An           3410000
Đồng Nai          3097107
dtype: int64
Top 5 tỉnh/tp diện tích lớn nhất Việt Nam 2023:
 Nghệ An      16493.0
Gia Lai      15536.9
Sơn La       14174.4
Đăk Lăk      13030.5
Thanh Hóa    11132.2
dtype: float64


vd4.5.1.3

In [13]:
#Tạo 2 Series A, B và tính tổng các giá trị
A=pd.Series([1,3,5],index=[0,1,2])
B=pd.Series([2,4,6],index=[1,2,3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [14]:
#Sử dụng ufuncs, truyền tham số fill_value vào.
A.add(B,fill_value=0)

0    1.0
1    5.0
2    9.0
3    6.0
dtype: float64

vd4.5.1.4

In [17]:
#Tạo 2 DataFrame Adf, Bdf và tính tổng các giá trị
import pandas as pd
import numpy as np
Adf=pd.DataFrame(np.random.randint(0,10,(2,2)), columns=['A','B'])
Bdf=pd.DataFrame(np.random.randint(0,10,(3,3)),columns=['B','A','C'])
print("Adf:\n",Adf)
print("Bdf:\n",Bdf)
print("\nAdf+Bdf: \n", Adf+Bdf)

Adf:
    A  B
0  6  8
1  0  8
Bdf:
    B  A  C
0  4  4  8
1  1  2  0
2  9  4  8

Adf+Bdf: 
       A     B   C
0  10.0  12.0 NaN
1   2.0   9.0 NaN
2   NaN   NaN NaN


In [18]:
print("Adf+Bdf(filled A):\n", Adf.add(Bdf,fill_value=0))

Adf+Bdf(filled A):
       A     B    C
0  10.0  12.0  8.0
1   2.0   9.0  0.0
2   4.0   9.0  8.0


# 4.5.2 Xử lý dữ liệu giữa Series và Dataframe

vd4.5.2.1

In [19]:
#Tạo một mảng NumPy 2 chiều (3,4) từ 10 phân tử ngẫu nhiên 0-->9
arr = np.random.randint(10,size=(3,4))
arr

array([[8, 6, 5, 2],
       [7, 7, 6, 2],
       [5, 4, 1, 4]], dtype=int32)

In [22]:
arr[0]

array([8, 6, 5, 2], dtype=int32)

In [20]:
arr-arr[0]

array([[ 0,  0,  0,  0],
       [-1,  1,  1,  0],
       [-3, -2, -4,  2]], dtype=int32)

In [21]:
#Tạo DataFrame df từ mảng NumPy arr, với các cột là P, Q, M, N
df = pd.DataFrame(arr,columns=['P','Q','M','N'])
print("df:\n",df)
#Tính toán hiệu của df với phần tử tương ứng trong hàng đầu của nó
df-df.iloc[0]

df:
    P  Q  M  N
0  8  6  5  2
1  7  7  6  2
2  5  4  1  4


P  Q  M  N
0  0  0  0  0
1 -1  1  1  0
2 -3 -2 -4  2

In [ ]:
df.iloc[0] # Lấy hàng đầu tiên của dataframe df dưới dạng series

P    8
Q    6
M    5
N    2
Name: 0, dtype: int32

In [24]:
df.iloc[0].index    #index of series lấy từ hnagf đầu tiên of dataframe df

Index(['P', 'Q', 'M', 'N'], dtype='object')

In [25]:
df.columns

Index(['P', 'Q', 'M', 'N'], dtype='object')

In [26]:
df.iloc[0].index=df.columns

In [27]:
df.iloc[0].name

0

In [28]:
df

P  Q  M  N
0  8  6  5  2
1  7  7  6  2
2  5  4  1  4

In [30]:
df-df.iloc[0]

P  Q  M  N
0  0  0  0  0
1 -1  1  1  0
2 -3 -2 -4  2

In [31]:
df

P  Q  M  N
0  8  6  5  2
1  7  7  6  2
2  5  4  1  4

In [32]:
df['Q'].index=df.index

# 4.5.3.Xử lý dữ liệu bị thiếu trong pandas

vd4.5.3.2

In [33]:
arr_nan=np.array([1,np.nan,3,4])
print(f"Mảng gốc: {arr_nan}")

Mảng gốc: [ 1. nan  3.  4.]


In [35]:
# Tính chất
arr_nan.sum(),arr_nan.max(), arr_nan.min()

(np.float64(nan), np.float64(nan), np.float64(nan))

In [37]:
#giải pháp nánum() (bỏ qua NaN)
np.nansum(arr_nan), np.nanmin(arr_nan)

(np.float64(8.0), np.float64(1.0))

vd4.5.3.3

In [38]:
import pandas as pd
sr_auto=pd.Series([1,2,np.nan,4,None])
sr

0    8
1    8
2    3
3    7
dtype: int32

vd4.5.3.6

In [40]:
data=pd.Series([1,np.nan,2,None,3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64